
        - name: Install Mysql
          apt:
                name: ['mysql-server','mysql-client']
                state: present
                update-cache: yes

        - name: Start MySQL Service
          service:
                name: mysql
                state: started
                enabled: yes

        - name: Start MySQL Service Shell
          shell: /etc/init.d/mysql start

        - name: Confirm MySQL is running
          command: /etc/init.d/mysql status
          register: mysql_status
          failed_when: "'stopped' in mysql_status.stdout"
          changed_when: False

        - name: Create Application Database
          mysql_db:
                name: "{{ db_name }}"
                state: present
                login_unix_socket: /run/mysqld/mysqld.sock

        - name: Create Application User
          mysql_user:
                name: "{{ db_user }}"
                password: "{{ db_password }}"
                priv: '*.*:ALL'
                state: present
                login_unix_socket: /var/run/mysqld/mysqld.sock


