     - name: Install all Dependancies
       apt:
        name: ['inetutils-ping','python','python-setuptools','python-dev','build-essential','python-pip','python-mysqldb']
        state: present
        update-cache: yes


